#!/usr/bin/env python3
from distutils import extension
import os
import shutil
import sys

inputDir = sys.argv[1]
outputDir = inputDir
cnt = int(sys.argv[2])
filesList = os.listdir(inputDir)
for i in filesList:
    extension = i.split(".")[-1]
    filenameNew = str(cnt)+"."+extension
    shutil.move(inputDir + i, outputDir + filenameNew)
    cnt += 1