#!/usr/bin/env python3
import sys
import os
import json
import argparse
import hashlib

parser = argparse.ArgumentParser(description='Tool to hash a file contents')
parser.add_argument("--source", type=str, help='Input dir for labels')
args = parser.parse_args()

INDIR = args.source
md5 = hashlib.md5()

print("Input dir: ", INDIR)

#read all files in the directory
classes = set()
counter = {}
for filename in os.listdir(INDIR):
    if filename.endswith(".json"):
        print("Processing file: ", filename)
        with open(INDIR + "/" + filename) as f:
            md5.update(f.read().encode('utf-8'))
            print("MD5: ", md5.hexdigest())
            