#!/usr/bin/env python3
import sys
import os
import json
import argparse

parser = argparse.ArgumentParser(description='Unique class lister in labelme format')
parser.add_argument("--source", type=str, help='Input dir for labels')
args = parser.parse_args()

INDIR = args.source

print("Input dir: ", INDIR)

#read all files in the directory
classes = set()
for filename in os.listdir(INDIR):
    if filename.endswith(".json"):
        print("Processing file: ", filename)
        with open(INDIR + "/" + filename) as f:
            data = json.load(f)
            for shape in data['shapes']:
                classes.add(shape['label'])

print("Unique classes: ", classes)
