#!/usr/bin/env python3
import os
import sys
import json
import cv2
import numpy as np


inputDir = sys.argv[1]
output_dir = "mask/"
#creating the ground_truth folder if it doesn't exist
os.makedirs(output_dir, exist_ok=True)

json_files = os.listdir(inputDir)
#loading the json file
for image_json in json_files:
    #neglect mask folder
    print(image_json)
    if image_json == "mask":
        continue
    with open(inputDir+image_json) as file:
        data = json.load(file)
    #replace . with _ in the filename
    filename = data["imagePath"].split("/")[-1]
    if "." in filename:
        splitted = filename.split(".")
        splitted = splitted[:-1]
        filename = ""
        for i in range(len(splitted)):
            filename += splitted[i]
    
    # creating a new ground truth image
    mask = np.zeros((data["imageHeight"], data["imageWidth"]), dtype='uint8')
    for shape in data['shapes']:
        mask = cv2.fillPoly(mask, [np.array(shape['points'], dtype=np.int32)], 255)

    # saving the ground truth masks
    cv2.imwrite(os.path.join(output_dir,filename) + ".png", mask)