#!/usr/bin/env python3
import sys
import os
import json
import argparse

parser = argparse.ArgumentParser(description='Unique class annotation counter')
parser.add_argument("--source", type=str, help='Input dir for labels')
args = parser.parse_args()

INDIR = args.source

print("Input dir: ", INDIR)

#read all files in the directory
classes = set()
counter = {}
for filename in os.listdir(INDIR):
    if filename.endswith(".json"):
        print("Processing file: ", filename)
        with open(INDIR + "/" + filename) as f:
            data = json.load(f)
            for shape in data['shapes']:
                classes.add(shape['label'])
                counter[shape['label']] += 1 if shape['label'] in counter else 1

print("Count of each  classe: ", counter)
