#!/usr/bin/env python3
import os
import sys
import json
import cv2
import numpy as np

inputDir = sys.argv[1]
fileCount = int(sys.argv[2])
output_dir = "filesWithLocation/"

#creating the ground_truth folder if it doesn't exist
os.makedirs(output_dir, exist_ok=True)

#changing the imagePath

json_files = os.listdir(inputDir)
#loading the json file
for image_json in json_files:
    if image_json == "filesWithLocation":
        continue
    with open(inputDir+image_json) as f:
        data = json.load(f)
        #changing the imagePath
        data["imagePath"] = str(fileCount) +".png"
        
        #saving the json file
        with open(output_dir+str(fileCount)+".json", "w") as fh:
            json.dump(data, fh)
        
        fileCount += 1