#!/usr/bin/env python3
import os
import sys
import json
import base64

inputDir = sys.argv[1]



#read the files in the input directory and generate the images with imageData
files = os.listdir(inputDir)
#create images directory
os.makedirs("images", exist_ok=True)
for file in files:
    if file == "images":
        continue
    with open(inputDir+file) as f:
        data = json.load(f)
        with open("images/"+file.split(".")[0]+".png", "wb") as fh:
            fh.write(base64.b64decode(data["imageData"]))
        
