#!/usr/bin/env python3
import os
import sys


folder = "/home/countai/playground/cvTools"
tools = os.listdir(folder)

for tool in tools:
    #check if its not me
    if tool == "listcvtools":
        continue
    #check if its .gitignore file
    if tool == ".gitignore":
        continue
    #check if its a readme file
    if tool == "README.md":
        continue
    #check if its directory
    if os.path.isdir(tool):
        continue
    #check if its python script
    if tool.endswith(".py"):
        continue
    #check if its executable
    print(tool)