#!/usr/bin/env python3
import os
import sys


bucketName = sys.argv[1]
folder = sys.argv[2]
# command = "s3fs "+bucketName+" "+folder+" -o passwd_file=/home/countai/.aws/pass -o dbglevel=info -f -o curldbg"
command = "s3fs "+bucketName+" "+folder+" -o passwd_file=/home/countai/.aws/pass "
os.system(command)
