#!/usr/bin/env python3
import os
import cv2
import random
import sys


folder = sys.argv[1]

try:
    os.mkdir(sys.argv[1]+"/jpg2png/")
except:
    pass


distDir = sys.argv[1]+"/jpg2png/"
for i in os.listdir(folder):
    if i == "jpg2png":
        continue
    img = cv2.imread(folder+i)
    # extension = i.split(".")[-1]
    i = i[:-3]
    print(distDir+i+"png")
    cv2.imwrite(distDir+i+"png",img)
    print(img.shape)
    