#!/usr/bin/env python3
import os
import sys
import time

#test and train split

inputDir = sys.argv[1]

trainRatio = sys.argv[2]

className = sys.argv[3]

#create the train and test folder
os.makedirs("train", exist_ok=True)
os.makedirs("val", exist_ok=True)

#create a folder for the class in the train and test folder
os.makedirs("train/"+className, exist_ok=True)
os.makedirs("val/"+className, exist_ok=True)

#list all the files in the input directory
files = os.listdir(inputDir)

#split the files into train and test
train = files[:int(len(files)*float(trainRatio))]
test = files[int(len(files)*float(trainRatio)):]

#copy the files into the train and test folder with random names with time.time()
for file in train:
    # os.system("cp '"+inputDir+file+"' train/")
    os.system("cp '"+inputDir+file+"' train/"+className+"/"+str(time.time())+file)
for file in test:
    # os.system("cp '"+inputDir+file+"' val/")
    os.system("cp '"+inputDir+file+"' val/"+className+"/"+str(time.time())+file)
    