#!/usr/bin/env python3
import sys
import os
import json
import argparse


parser = argparse.ArgumentParser(description='Unique class lister in labelme format')
parser.add_argument("--source", type=str, help='Input dir for labels')
args = parser.parse_args()


INDIR = args.source
print("Input dir: ", INDIR)
OUTDIR = INDIR + "_EmptyLabels"
print("Output dir: ", OUTDIR)
os.makedirs(OUTDIR, exist_ok=True)

#read all image files in the directory and create a empty file for each
for filename in os.listdir(INDIR):
    if filename.endswith(".jpg"):
        #create a empty .txt file
        print("Processing file: ", filename)
        with open(OUTDIR + "/" + filename[:-4] + ".txt", 'w') as outfile:
            outfile.write("")
        


        
        